### ISSUE TITLE
A qustion about the sample program

### ISSUE THREAD

**Issue by Lumos1110** [mhobbs18/BB_PD#9]
Hello author. I can't seem to find the sample program 'Beam_3_UN_DX5mm.mat' that you mentioned in the readme. And when I type MAIN('Beam_3_UN_DX5mm.mat', 8), the program says that the number of outputs to the right of the equal sign is not enough to satisfy the assignment requirement.

**Comment by mark-hobbs** [comment]
Hey, `Beam_3_UN_DX5mm.mat` is an input file. Unfortunately it is too large to store within the repo so you need to create this file using the input module. 

This package was developed during my PhD, and due to my limited development experience at the time, it has multiple issues, with various features likely to be broken. Although fixing and leveraging the package should be relatively straightforward, it may demand a significant time investment that I am unable to commit to. Additionally, I have transitioned away from MATLAB and no longer have access to a license.

Perhaps, you can refer to the examples provided in [PyPD](https://github.com/mark-hobbs/PyPD) - a Python package that I have been slowly developing. The easiest way to get started is by running the following crack branching example in Google Colab

<a href="https://colab.research.google.com/github/mark-hobbs/PyPD/blob/main/examples/crack_branching.ipynb" target="_parent">
<img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>
